### ISSUE TITLE
Wrong results in `nn` function for `euclidean` method

### ISSUE THREAD

**Issue by ManosPapadakis95** [ManosPapadakis95/Rnanoflann#4]
The result of the function for `euclidean` method is wrong. For now, as an extra step, just square root the `distances` and don't use the argument `square`.

```R
a <- Rnanoflann::nn(x, points)
sqrt(a$distances)
```

**Comment by jlblancoc** [comment]
For what it can be of help: nanoflann input and output distances are always squared...

**Comment by ManosPapadakis95** [comment]
Yes Professor, I know it. The bug is for my own implementation.
